name: qt_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
      - PySide6==6.7.3
      - PySide6_Addons==6.7.3
      - PySide6_Essentials==6.7.3
      - shiboken6==6.7.3
      - pip==25.3
      - setuptools==80.9.0
      - wheel==0.45.1
